version: "3"

volumes:
  evmapp-1-data:
  evmapp-snark-keys:

networks:
  evmapp_network:

services:
  evm-app:
    image: zencash/evmapp:${SDK_COMMITTISH_EVMAPP}
    container_name: evmapp-1
    restart: always
    build:
      context: ./configs
      dockerfile: Dockerfile
      args:
        - "ARG_SDK_VERSION=${SDK_VERSION_EVMAPP}"
        - "SDK_COMMITTISH=${SDK_COMMITTISH_EVMAPP}"
    networks:
      - evmapp_network
    ports:
      - "${SCNODE_REST_PORT}:${SCNODE_REST_PORT}"
      - "${SCNODE_NET_P2P_PORT}:${SCNODE_NET_P2P_PORT}"
    volumes:
      - "evmapp-1-data:/sidechain/datadir:rw"
      - "evmapp-snark-keys:/sidechain/snark_keys:rw"
      - "./logs/evmapp-1:/sidechain/logs:rw"
      - "./configs/evmapp_settings.conf.tmpl:/sidechain/config/sc_settings.conf.tmpl:ro"
    environment:
      - "LOCAL_GRP_ID=${SCNODE_GRP_ID}"
      - "LOCAL_USER_ID=${SCNODE_USER_ID}"
      - SCNODE_BACKUP_TAR_GZ_URL
      - SCNODE_CERT_SIGNERS_MAXPKS
      - SCNODE_CERT_SIGNERS_PUBKEYS
      - SCNODE_CERT_SIGNERS_THRESHOLD
      - "SCNODE_CERT_SIGNING_ENABLED=false"
      - "SCNODE_CERT_SUBMITTER_ENABLED=false"
      - SCNODE_FORGER_ALLOWED_FORGERS
      - "SCNODE_FORGER_ENABLED=false"
      - SCNODE_FORGER_RESTRICT
      - SCNODE_GENESIS_BLOCKHEX
      - SCNODE_GENESIS_SCID
      - SCNODE_GENESIS_POWDATA
      - SCNODE_GENESIS_MCBLOCKHEIGHT
      - SCNODE_GENESIS_MCNETWORK
      - SCNODE_GENESIS_WITHDRAWALEPOCHLENGTH
      - SCNODE_GENESIS_COMMTREEHASH
      - SCNODE_NET_KNOWNPEERS
      - SCNODE_NET_MAGICBYTES
      - "SCNODE_NET_NODENAME=${SCNODE_NET_NODENAME}"
      - "SCNODE_NET_P2P_PORT=${SCNODE_NET_P2P_PORT}"
      - SCNODE_REST_PORT
      - "SCNODE_WALLET_GENESIS_SECRETS=${SCNODE_WALLET_GENESIS_SECRETS}"
      - SCNODE_WALLET_MAXTX_FEE
      - "SCNODE_WALLET_SEED=${SCNODE_WALLET_SEED}"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "4"
