version: "3"

volumes:
  data:
  snark-keys:

networks:
  evmapp_network:

services:
  evmapp:
    image: horizenlabs/evmapp:${SC_COMMITTISH_EVMAPP}
    container_name: evmapp
    restart: always
    networks:
      - evmapp_network
    ports:
      - "127.0.0.1:${SCNODE_REST_PORT}:${SCNODE_REST_PORT}"
      - "${SCNODE_NET_P2P_PORT}:${SCNODE_NET_P2P_PORT}"
    volumes:
      - "data:/sidechain/datadir:rw"
      - "snark-keys:/sidechain/snark_keys:rw"
      - "./logs/evmapp:/sidechain/logs:rw"
    environment:
      - "LOCAL_GRP_ID=${SCNODE_GRP_ID}"
      - "LOCAL_USER_ID=${SCNODE_USER_ID}"
      - SCNODE_BACKUP_TAR_GZ_URL
      - SCNODE_CERT_SIGNERS_MAXPKS
      - SCNODE_CERT_SIGNERS_PUBKEYS
      - SCNODE_CERT_MASTERS_PUBKEYS
      - SCNODE_CERT_SIGNERS_THRESHOLD
      - SCNODE_CERT_SIGNING_ENABLED
      - SCNODE_CERT_SUBMITTER_ENABLED
      - SCNODE_REMOTE_KEY_MANAGER_ENABLED
      - SCNODE_FORGER_ENABLED
      - SCNODE_ALLOWED_FORGERS
      - SCNODE_FORGER_RESTRICT
      - SCNODE_GENESIS_BLOCKHEX
      - SCNODE_GENESIS_SCID
      - SCNODE_GENESIS_POWDATA
      - SCNODE_GENESIS_MCBLOCKHEIGHT
      - SCNODE_GENESIS_MCNETWORK
      - SCNODE_GENESIS_WITHDRAWALEPOCHLENGTH
      - SCNODE_GENESIS_COMMTREEHASH
      - SCNODE_GENESIS_ISNONCEASING
      - SCNODE_WS_CLIENT_ENABLED
      - SCNODE_NET_KNOWNPEERS
      - SCNODE_NET_MAGICBYTES
      - SCNODE_NET_NODENAME
      - SCNODE_NET_P2P_PORT
      - SCNODE_NET_API_LIMITER_ENABLED
      - SCNODE_NET_SLOW_MODE
      - SCNODE_REST_PASSWORD
      - SCNODE_REST_PORT
      - SCNODE_WALLET_SEED
      - SCNODE_WALLET_MAXTX_FEE
      - SCNODE_WS_SERVER_PORT
      - SCNODE_WS_SERVER_ENABLED
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "4"
